[package]
name = "design_patterns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "singleton"
path = "src/singleton.rs"


[[bin]]
name = "factory"
path = "src/factory.rs"
